<a href="https://colab.research.google.com/github/Crashed-cpu/aws-ml-py/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import pandas as pd

In [67]:
lst = [i for i in range(384, 9348, 1294)]
lst
df = pd.Series(lst)
df

0     384
1    1678
2    2972
3    4266
4    5560
5    6854
6    8148
dtype: int64

In [68]:
df = pd.Series(data=lst, index=['aaja', 'baaja', 'paaja', 'saaja','a','s','si'])

In [69]:
df

aaja      384
baaja    1678
paaja    2972
saaja    4266
a        5560
s        6854
si       8148
dtype: int64

In [70]:
df.describe()

count       7.000000
mean     4266.000000
std      2795.359488
min       384.000000
25%      2325.000000
50%      4266.000000
75%      6207.000000
max      8148.000000
dtype: float64

In [71]:
# pd.Series?

In [72]:
# 2d
import pandas as pd
data = {
    "name": ['nikhil', 'raj', 'devendra', 'hello'],
    'age': [10,20,30,40]
}
df = pd.Series(data) # 1d
print(df)
# 2d
df2 = pd.DataFrame(data)
df2

name    [nikhil, raj, devendra, hello]
age                   [10, 20, 30, 40]
dtype: object

       name  age
0    nikhil   10
1       raj   20
2  devendra   30
3     hello   40

In [73]:
data = [
    ['nikhil', 10],
    ['raj', 20],
    ['devendra', 30],
    ['hello', 40]
]
df = pd.DataFrame(data, columns=['name', 'age'])
print(df)

       name  age
0    nikhil   10
1       raj   20
2  devendra   30
3     hello   40

In [74]:
#add indexing name
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'], columns=['name', 'age'])
print(df)
#

       name  age
a    nikhil   10
b       raj   20
c  devendra   30
d     hello   40

In [75]:
url = 'https://raw.githubusercontent.com/Crashed-Cpu/aws-ml-py/main/file.csv'
print('By Ayush Saini 23EACAD025\n\n')
df = pd.read_csv(url)
print(df)

# github_csv file export

df.to_csv("file2.csv")

By Ayush Saini 23EACAD025


       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male

In [76]:
url = 'https://raw.githubusercontent.com/Crashed-Cpu/aws-ml-py/main/file.xlsx'
print('By Ayush Saini 23EACAD025\n\n')
df = pd.read_excel(url)
print(df)

# github_excel file export

df.to_excel("file2.xlsx")

By Ayush Saini 23EACAD025


       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male

In [77]:
url = 'https://raw.githubusercontent.com/Crashed-Cpu/aws-ml-py/main/data%20(1).json'
print('By Ayush Saini 23EACAD025\n\n')
df = pd.read_json(url)
print(df)

# github_json file export

df.to_json("file2.json")

By Ayush Saini 23EACAD025


       name  age
0    nikhil   10
1  devendra   20
2       raj   30
3     hello   40